# Generated by Django 5.1.4 on 2026-07-03 14:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_is_premium_post_premium_price_userpostaccess'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='early_access_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='patron_perks',
            field=models.TextField(blank=True, default='Everything in Supporter + Direct messages'),
        ),
        migrations.AddField(
            model_name='profile',
            name='patron_price',
            field=models.DecimalField(decimal_places=2, default=15.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='profile',
            name='supporter_perks',
            field=models.TextField(blank=True, default='Early access to posts, No ads'),
        ),
        migrations.AddField(
            model_name='profile',
            name='supporter_price',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=6),
        ),
        migrations.CreateModel(
            name='AuthorSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('free', 'Free'), ('supporter', 'Supporter'), ('patron', 'Patron')], default='free', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to=settings.AUTH_USER_MODEL)),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('subscriber', 'author')},
            },
        ),
    ]
