# Generated by Django 5.1.4 on 2026-07-06 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_advertisement'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='covers/'),
        ),
        migrations.AddField(
            model_name='post',
            name='cover_image_blur',
            field=models.TextField(blank=True),
        ),
    ]
