# Generated by Django 5.1.4 on 2026-07-07 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_cover_image_post_cover_image_blur'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='compressed_image_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='original_image_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
